services:
  db:
    image: mysql:8.0
    container_name: tienda-db
    environment:
      MYSQL_DATABASE: tienda_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./tienda-backend
      dockerfile: Dockerfile
    container_name: tienda-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=tienda_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      db:
        condition: service_started
    restart: always

networks:
  default:
    name: tienda-network
